- name: ensure github.com is a known host
  known_hosts:
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    host: "github.com"

- name: installing mailcatcher gem dependencies
  apt: name={{item}} state=present
  sudo: yes
  with_items:
    - sqlite3
    - libsqlite3-dev

- name: Install mailcatcher gem
  gem: name=mailcatcher state=present user_install=no
  sudo: yes

- name: bundle install
  command:  bundle install --clean --jobs 2 --path vendor/bundle
  args:
    chdir: ~/project

- name: create development pg user
  postgresql_user: name=developmentuser password=enter123 role_attr_flags=CREATEDB,SUPERUSER
  sudo: yes
  sudo_user: postgres

- name: create database.yml
  command:  cp config/example/database.yml config/database.yml
  args:
    chdir: ~/project
    creates: ~/project/config/database.yml

- name: rake db:create db:migrate db:seed
  command: bundle exec rake db:create db:migrate db:seed
  args:
    chdir: ~/project

- name: rake db:create RAILS_ENV=test
  command: bundle exec rake db:create RAILS_ENV=test
  args:
    chdir: ~/project

- name: Install PhantomJS 1.9.8
  sudo: yes
  script: _scripts/install_phantomjs.sh creates=/usr/local/bin/phantomjs
