- name: ensure github.com is a known host
  known_hosts:
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    host: "github.com"

- name: installing mailcatcher gem dependencies
  apt: name={{item}} state=present
  sudo: yes
  with_items:
    - sqlite3
    - libsqlite3-dev

- name: Install mailcatcher gem
  gem: name=mailcatcher state=present user_install=no
  sudo: yes

- name: bundle install
  command:  bundle install --clean --jobs 2 --path vendor/bundle
  args:
    chdir: ~/project

- name: create development pg user
  postgresql_user: name=developmentuser password=enter123 role_attr_flags=CREATEDB,NOSUPERUSER
  sudo: yes
  sudo_user: postgres

- name: rake db:setup
  command: bundle exec rake db:setup
  args:
    chdir: ~/project
