- name: ensure github.com is a known host
  sudo: no
  known_hosts:
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    host: "github.com"

- name: bundle install
  command:  bundle install --clean --jobs 2 --path vendor/bundle
  sudo: no
  args:
    chdir: ~/project

- name: create development pg user
  postgresql_user: name=developmentuser password=enter123 role_attr_flags=CREATEDB,NOSUPERUSER
  sudo: yes
  sudo_user: postgres

- name: rake db:setup
  command: bundle exec rake db:setup
  sudo: no
  args:
    chdir: ~/project
