---
detectors:
  TooManyStatements:
    max_statements: 6
  UtilityFunction:
    public_methods_only: true
  IrresponsibleModule:
    enabled: false
  Attribute:
    enabled: false
  LongParameterList:
    max_params: 5

directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false  
  "app/helpers":
    UtilityFunction:
      enabled: false
  "test/support":
    UtilityFunction:
      enabled: false
  "db/migrate":
    UncommunicativeVariableName:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    DuplicateMethodCall:
      enabled: false

exclude_paths:
  - vendor
  