AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'Vagrantfile'

Metrics/LineLength:
  Max: 120

Metrics/ParameterLists:
  Max: 7
  CountKeywordArgs: true

Style/ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

Rails/Validation:
  Enabled: false

Performance/RedundantMerge:
  Enabled: false