AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 120

Metrics/ParameterLists:
  Max: 7
  CountKeywordArgs: true

Style/ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

Rails/Validation:
  Enabled: false
