version: '3.2'

volumes:
  postgres-11-data:
    driver: local
  bundle-data:
    driver: local

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-11-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - OPENSSL_CONF=/etc/ssl/
    volumes:
      - .:/usr/src/app
      - bundle-data:/usr/local/bundle
    depends_on:
      - db

  web_rails:
    build: .
    environment:
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=1
    command: ./run.sh
    volumes:
      - .:/usr/src/app
      - bundle-data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

  web_cypress:
    build: .
    environment:
    - RAILS_ENV=test
    - RAILS_MAX_THREADS=1
    - PORT=5002
    command: ./run.sh
    volumes:
    - .:/usr/src/app
    - bundle-data:/usr/local/bundle
    ports:
    - "5002:5002"
    depends_on:
    - db

  webpack_dev:
    build: .
    environment:
      - RAILS_ENV=development
    command: webpack --colors --progress --watch
    volumes:
      - .:/usr/src/app
      - bundle-data:/usr/local/bundle