---
galaxy_info:
  author: George Miroshnykov
  description: Provision NewRelic System Monitor
  company: Rebbix
  license: BSD
  min_ansible_version: 1.4

  platforms:
  - name: Ubuntu
    versions:
    - precise

  categories:
  - monitoring
