- name: create app user
  user: name=gc_user shell=/bin/bash createhome=yes

- name: Set up authorized_keys for the app users
  authorized_key: user=gc_user key="{{ app_key }}"

- name: create shared directory
  file: path=/home/gc_user/shared state=directory mode=775 owner=gc_user group=gc_user

- name: create shared directories
  file: path=/home/gc_user/shared/{{item}} state=directory mode=775 owner=gc_user group=gc_user
  with_items:
    - config
    - log

- name: update puma.rb
  template: src=home/gc_user/shared/puma.rb.j2 dest=/home/gc_user/shared/puma.rb mode=644 owner=gc_user group=gc_user

- name: update database.yml
  template: src=home/gc_user/shared/config/database.yml.j2 dest=/home/gc_user/shared/config/database.yml mode=644 owner=gc_user group=gc_user

- name: update secrets.yml
  template: src=home/gc_user/shared/config/secrets.yml.j2 dest=/home/gc_user/shared/config/secrets.yml mode=644 owner=gc_user group=gc_user

- name: update newrelic.yml
  template: src=home/gc_user/shared/config/newrelic.yml.j2 dest=/home/gc_user/shared/config/newrelic.yml mode=644 owner=gc_user group=gc_user
