- name: ensure github.com is a known host
  known_hosts:
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    host: "github.com"

- name: add brightbox ruby repo
  apt_repository: repo='ppa:brightbox/ruby-ng' update_cache=yes

- name: Install ruby2.2 and ruby-switch
  apt: name={{item}} state=present
  notify: switch ruby
  with_items:
    - ruby2.2
    - ruby2.2-dev
    - ruby-switch

- name: Install Bundler
  gem: name=bundler user_install=no state=latest

- name: installing gem dependencies
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - libpq-dev
    - libssl-dev
    - postgresql-client
    - g++
    - git