- name: installing mailcatcher gem dependencies
  apt: name={{item}} state=present
  sudo: yes
  with_items:
    - sqlite3
    - libsqlite3-dev

- name: Install mailcatcher gem
  gem: name=mailcatcher state=present user_install=no
  sudo: yes
