- name: ensure github.com is a known host
  known_hosts:
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    host: "github.com"

- include: ruby.yml
- include: tools.yml
- include: aws_eb.yml
- include: heroku.yml

- name: create .env
  command:  cp config/examples/.env.vagrant .env
  sudo: no
  args:
    chdir: ~/project
    creates: ~/project/.env

- name: app setup
  command: bin/setup.sh
  sudo: no
  args:
    chdir: ~/project
