- name: ensure github.com is a known host
  known_hosts:
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    host: "github.com"

- include: ruby.yml
- include: tools.yml
- include: aws_eb.yml

- name: bundle install
  command:  bundle install --jobs 4 --retry 2 --path vendor/bundle
  sudo: no
  args:
    chdir: ~/project
    creates: ~/project/vendor/bundle

- name: create .env
  command:  cp config/examples/.env.vagrant .env
  sudo: no
  args:
    chdir: ~/project
    creates: ~/project/.env
