- name: installing postgresql-client
  apt: name=postgresql-client state=present

- name: installing mailcatcher gem dependencies
  apt: name={{item}} state=present
  sudo: yes
  with_items:
    - sqlite3
    - libsqlite3-dev

- name: Install gems
  gem: name={{item}} state=present user_install=no
  sudo: yes
  with_items:
    - brakeman
    - mailcatcher
    - rubocop

- name: Install PhantomJS 1.9.8
  sudo: yes
  script: _scripts/install_phantomjs.sh creates=/usr/local/bin/phantomjs
