# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8bc90ebae2a4fa9d6726b907c04d3dd9971ace45a4f44be4a0a002350c6ce58c0fcd161a93b31e6fddcd1d7dd3438455b13fac0418c3ca3b52b07e8bfc36c94
  cms_user: admin
  cms_password: admin

test:
  secret_key_base: a974c0365fad81fd7221009e1d16077a03fc8e0c9e8a1199001731954714443dfcac166a09862f04d50dddda512d03361e99eeeeca2e70f55e48e1ac83df67c8
  cms_user: admin
  cms_password: admin

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f8bc90ebae2a4fa9d6726b907c04d3dd9971ace45a4f44be4a0a002350c6ce58c0fcd161a93b31e6fddcd1d7dd3438455b13fac0418c3ca3b52b07e8bfc36c94
  cms_user: admin
  cms_password: admin
