---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: install postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Ensure PostgreSQL is running
  service: name=postgresql state=started

- name: wait for PostgreSQL to be running
  wait_for: port=5432 delay=2

- name: create my_grocery_price_book_www on database
  postgresql_db: name={{app_deploy_name}} encoding='UTF-8'
  sudo: yes
  sudo_user: postgres

- name: create my_grocery_price_book_www pg vagrant user
  postgresql_user: name=my_grocery_price_book_www role_attr_flags=CREATEDB,SUPERUSER
  sudo: yes
  sudo_user: postgres

- name: add app ip addresses to pg_hba.conf
  lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf line="host all all {{app_host}}/24 trust"
  sudo: yes
  sudo_user: postgres
  notify: restarting postgresql

- name: update postgresql.conf
  copy: src=etc/postgresql/9.3/main/postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf owner=postgres group=postgres mode=0644
  notify: restarting postgresql
