---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: install postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Ensure PostgreSQL is running
  service: name=postgresql state=started

- name: wait for PostgreSQL to be running
  wait_for: port=5432 delay=2

- name: create ansible_ssh_user on postgres
  postgresql_user: name={{ansible_ssh_user}} role_attr_flags=CREATEDB,NOSUPERUSER
  sudo: yes
  sudo_user: postgres

- name: add app ip addresses to pg_hba.conf
  lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf line="host all all 192.168.30.15/24 trust"
  sudo: yes
  sudo_user: postgres
  notify: restarting postgresql

- name: update postgresql.conf
  copy: src=etc/postgresql/9.3/main/postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf owner=postgres group=postgres mode=0644
  notify: restarting postgresql
