---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: install postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Ensure PostgreSQL is running
  service: name=postgresql state=started

- name: create my_grocery_cocktail on database
  postgresql_db: name=my_grocery_cocktail encoding='UTF-8'
  sudo: yes
  sudo_user: postgres

- name: create gc_user on postgres
  postgresql_user: db=my_grocery_cocktail name=gc_user password={{app_db_password}} role_attr_flags=CREATEDB,NOSUPERUSER
  sudo: yes
  sudo_user: postgres

- include: setup_backups.yml
